"""Add isbn column to borrowed_books

Revision ID: 0f0023f3f719
Revises: f96f0be855fc
Create Date: 2025-07-18 14:00:23.578970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0023f3f719'
down_revision: Union[str, Sequence[str], None] = 'f96f0be855fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_books', 'isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('isbn', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
