"""Add isbn column to borrowed_books

Revision ID: 5d89e03095b1
Revises: 0f0023f3f719
Create Date: 2025-07-18 14:02:35.452466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d89e03095b1'
down_revision: Union[str, Sequence[str], None] = '0f0023f3f719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('isbn', sa.String(), nullable=False))
    op.create_foreign_key(None, 'borrowed_books', 'books', ['isbn'], ['isbn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrowed_books', type_='foreignkey')
    op.drop_column('borrowed_books', 'isbn')
    # ### end Alembic commands ###
