"""Make Borrowed_book nullable

Revision ID: 752156150dfb
Revises: 58a6f8762894
Create Date: 2025-07-18 00:44:11.312612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752156150dfb'
down_revision: Union[str, Sequence[str], None] = '58a6f8762894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Borrowed_book',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Borrowed_book',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
