"""Add isbn column to borrowed_books

Revision ID: f694fe7353b7
Revises: 752156150dfb
Create Date: 2025-07-18 12:53:42.334198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f694fe7353b7'
down_revision: Union[str, Sequence[str], None] = '752156150dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Borrowed_book')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Borrowed_book', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
